const host = "http://localhost:5000";
export const sockethost = "http://localhost:5000";
export const loginRoute = `${host}/api/v1/users/signin`;
export const registerRoute = `${host}/api/v1/users/signup`;
export const logoutRoute = `${host}/api/v1/users/logout`;
export const allUsersRoute = `${host}/api/v1/users/getAllUsersNotMe`;
export const sendMessageRoute = `${host}/api/v1/messages/sendmsg`;
export const recieveMessageRoute = `${host}/api/v1/messages/getmsg`;
export const setAvatarRoute = `${host}/api/v1/users/setavatar`;
